spring.application.name=book-service
spring.datasource.url=jdbc:postgresql://localhost:5432/book_service
spring.datasource.username=postgres
spring.datasource.password=****
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
management.endpoints.web.exposure.include=health,info,metrics
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
#spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/book_service